DATASETS_FOLDER = "E:/Documenti/Uni/Magistrale/Tesi/Datasets/"

CRIMES_FOLDER = DATASETS_FOLDER + "Crimini/"
FINANCE_FOLDER = DATASETS_FOLDER + "Economia/"
POLITICS_FOLDER = DATASETS_FOLDER + "Politica/"
HEALTH_FOLDER = DATASETS_FOLDER + "Salute/"
RELIGION_FOLDER = DATASETS_FOLDER + "Religione/"

MIXED_FOLDER = DATASETS_FOLDER + "Misto/"


INPUT_PATH = "/user/73576/sdf/input/"
POLITICS_PATH = INPUT_PATH + "politics/"
MEDICAL_PATH = INPUT_PATH + "medical/"
FINANCE_PATH = INPUT_PATH + "finance/"
RELIGION_PATH = INPUT_PATH + "religion/"
